# Generated by Django 3.1.6 on 2021-02-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('registered_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
