# Generated by Django 3.1.6 on 2021-02-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=255)),
                ('ownerName', models.CharField(max_length=255)),
                ('aptNotes', models.TextField()),
                ('aptDate', models.DateField()),
            ],
        ),
    ]
