# Generated by Django 3.1.6 on 2021-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='aptDate',
            field=models.DateTimeField(),
        ),
    ]
